# Generated by Django 5.2.4 on 2025-07-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_date_joined_and_more'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminrole',
            old_name='admin',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='adminrole',
            unique_together={('user', 'role')},
        ),
    ]
